/**
 * Deploys MockUSDC + FlightMarket to a running anvil node (http://127.0.0.1:8545),
 * mints 10,000 USDC to the first three anvil accounts, and writes oracle/.env
 * and web/.env.local so the whole stack points at the fresh deployment.
 *
 *   anvil                    # terminal 1
 *   npm run deploy:local     # terminal 2 (in oracle/)
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { ContractFactory, JsonRpcProvider, Wallet, parseUnits } from "ethers";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "../../..");

// anvil's default deterministic accounts
export const ANVIL_KEYS = [
  "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80",
  "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d",
  "0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a",
];

export function artifact(name: string): { abi: any; bytecode: string } {
  const p = path.join(ROOT, "contracts", "out", `${name}.sol`, `${name}.json`);
  const a = JSON.parse(readFileSync(p, "utf8"));
  return { abi: a.abi, bytecode: a.bytecode.object };
}

export async function deployStack(rpcUrl: string) {
  const provider = new JsonRpcProvider(rpcUrl);
  provider.pollingInterval = 200;
  const deployer = new Wallet(ANVIL_KEYS[0], provider);

  const usdcArt = artifact("MockUSDC");
  const usdc = await new ContractFactory(usdcArt.abi, usdcArt.bytecode, deployer).deploy();
  await usdc.waitForDeployment();

  const fmArt = artifact("FlightMarket");
  const fm = await new ContractFactory(fmArt.abi, fmArt.bytecode, deployer).deploy(
    await usdc.getAddress(),
    deployer.address, // deployer doubles as oracle locally
  );
  await fm.waitForDeployment();

  for (const key of ANVIL_KEYS) {
    const who = new Wallet(key).address;
    await (await (usdc as any).mint(who, parseUnits("10000", 6))).wait();
  }

  return {
    provider,
    deployer,
    usdcAddress: await usdc.getAddress(),
    flightMarketAddress: await fm.getAddress(),
  };
}

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1]);
if (isMain) {
  const rpc = process.env.RPC_URL ?? "http://127.0.0.1:8545";
  deployStack(rpc).then(({ usdcAddress, flightMarketAddress, deployer }) => {
    const oracleEnv = `# generated by deploy:local
RPC_URL=${rpc}
ORACLE_PRIVATE_KEY=${ANVIL_KEYS[0]}
USDC_ADDRESS=${usdcAddress}
FLIGHT_MARKET_ADDRESS=${flightMarketAddress}
DATABASE_URL=file:./prisma/dev.db
ADMIN_SECRET=local-admin-secret
FLIGHT_PROVIDER=mock
MOCK_DEPARTS_IN_SEC=90
MOCK_FLIGHT_DURATION_SEC=60
WATCHER_INTERVAL_MS=5000
INDEXER_INTERVAL_MS=3000
INGEST_INTERVAL_MS=300000
PORT=4000
`;
    writeFileSync(path.join(ROOT, "oracle", ".env"), oracleEnv);
    const webEnv = `# generated by deploy:local
NEXT_PUBLIC_API_URL=http://localhost:4000
NEXT_PUBLIC_RPC_URL=${rpc}
NEXT_PUBLIC_CHAIN_ID=31337
NEXT_PUBLIC_USDC_ADDRESS=${usdcAddress}
NEXT_PUBLIC_FLIGHT_MARKET_ADDRESS=${flightMarketAddress}
`;
    writeFileSync(path.join(ROOT, "web", ".env.local"), webEnv);
    console.log(`MockUSDC:     ${usdcAddress}`);
    console.log(`FlightMarket: ${flightMarketAddress}`);
    console.log(`oracle:       ${deployer.address}`);
    console.log("Wrote oracle/.env and web/.env.local");
  });
}
